Munchin.BookStore/Munchin.BookStore/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Munchin.BookStore.Repository;
using System.Threading.Tasks;

namespace Munchin.BookStore.Components
{
    public class TopBooksViewComponent : ViewComponent
    {
        private readonly IBookRepositry _bookRepositry;

        public TopBooksViewComponent( IBookRepositry bookRepositry )
        {
            _bookRepositry = bookRepositry;
        }
        public async Task<IViewComponentResult> InvokeAsync( int count )
        {
            var books = await _bookRepositry.GetTopBooksAsync( count );
            return View( books );
        }
    }
}

Munchin.BookStore/Munchin.BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Munchin.BookStore.Models;
using Munchin.BookStore.Repository;

namespace Munchin.BookStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly NewBookAlertConfig _newBookAlertconfiguration;
        private readonly NewBookAlertConfig _thirdPartyBookconfiguration;
        private readonly IMessageRepository _messageRepository;

        public HomeController( IOptionsSnapshot<NewBookAlertConfig> newBookAlertconfiguration,
                               IMessageRepository messageRepository )
        {
            _newBookAlertconfiguration = newBookAlertconfiguration.Get( "InternalBook" );
            _thirdPartyBookconfiguration = newBookAlertconfiguration.Get( "ThirdPartyBook" );
            _messageRepository = messageRepository;
        }
        public ViewResult Index( )
        {
            bool IsDisplay = _newBookAlertconfiguration.DisplayNewBookAlert;
            bool IsDisplay1 = _thirdPartyBookconfiguration.DisplayNewBookAlert;

            //var value = _messageRepository.GetName();

            //var newBook = configuration.GetSection( "NewBookAlert" );
            //var result = newBook.GetValue<bool>( "DisplayNewBookAlert" );
            //var bookName = newBook.GetValue<string>( "BookName" );

            //var result = configuration["AppName"];
            //var key1 = configuration["infoObj:key1"];
            //var key2 = configuration["infoObj:key2"];
            //var key3 = configuration["infoObj:key3:key3obj1"];
            return View();
        }

        public ViewResult AboutUs( string name )
        {
            return View();
        }
        public ViewResult ContactUs( )
        {
            return View();
        }
    }
}

Munchin.BookStore/Munchin.BookStore/Views/Home/AboutUs.cshtml
@{ ViewData["Title"] = "About Us"; }

<h1>This is the about page of the application</h1>

Munchin.BookStore/Munchin.BookStore/Views/Home/ContactUs.cshtml
@{ ViewData["Title"] = "Contact Us"; }

<h1>Contact Us</h1>

Munchin.BookStore/Munchin.BookStore/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home"; }
@inject Munchin.BookStore.Repository.IBookRepositry _bookRepository

<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to Bookstore</h1>
        <p class="lead text-muted">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search books</a>
        </p>

        @*@foreach(var item in await _bookRepository.GetAllBooks())
            {
                <h2>@item.Title</h2>
            }*@

    </div>
</section>


<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">Top Books</h3>
        @await Component.InvokeAsync( "TopBooks", new { count = 3 } )

        @*<vc:top-books count="6"></vc:top-books>*@

    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            //alert("document is ready");
        })
    </script>
}